### ISSUE TITLE
Please allow selection of python version

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/PythonMagick#6]
Hi please allow selection of python version. patch will follow

**Comment by bastien-roucaries** [comment]
diff --git a/configure.ac b/configure.ac
index 99278ef..94ee01f 100644
--- a/configure.ac
+++ b/configure.ac
@@ -27,14 +27,24 @@ AC_PROG_INSTALL
 AC_PROG_LN_S
 AC_PROG_MAKE_SET
 AC_PROG_LIBTOOL
-AM_PATH_PYTHON([2.4])
 PKG_PROG_PKG_CONFIG
 
 # Add configure option --enable-maintainer-mode which enables dependency
 # checking and generation useful to package maintainers.  This is made an
 # option to avoid confusing end users.
+
+AC_ARG_WITH([python-min-version],
+        [AS_HELP_STRING([--with-python-min-version=version : python version to use])],
+        [PYTHON_MIN_VERSION="$withval"],
+        [PYTHON_MIN_VERSION="2.4"])
 AM_MAINTAINER_MODE
 
+AX_COMPARE_VERSION($PYTHON_MIN_VERSION, lt, 2.4,AC_MSG_ERROR([Python version not supported]))
+AC_MSG_CHECKING([for python with minimal version])
+AC_MSG_RESULT([$PYTHON_MIN_VERSION])
+AM_PATH_PYTHON([$PYTHON_MIN_VERSION])
+AX_PYTHON_DEVEL([>= '$PYTHON_MIN_VERSION'])
+
 # Checks for libraries.
 AX_BOOST_BASE
 AX_BOOST_PYTHON
`

**Comment by mikayla-grace** [comment]
We applied the patch you submitted.  Thanks.
