### ISSUE TITLE
Apply build fix patch

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/PythonMagick#7]
From 1ac5a6ab1d079702dbb6776759d8c4356bdf55f6 Mon Sep 17 00:00:00 2001
From: Thomas Viehmann tv@beamnet.de
Date: Thu, 8 Oct 2015 13:29:05 -0700
Subject: autotools related fixes

 Use python?.?-config instead of locate in python detection macro and don't link
 against libpython2.x.
 Fix python boost detection and reverse upstream's hardcoding of the lib in
 Makefile.am.
Last-Update: 2014-08-13
## Patch-Name: 001_autofoo_fixes.diff

 Makefile.am | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/Makefile.am b/Makefile.am
index bfcd21c..f0a5ea0 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -27,7 +27,7 @@ nodist_EXTRA__PythonMagick_la_SOURCES = dummy.cpp
 _PythonMagick_la_LDFLAGS = -avoid-version -module $(BOOST_LDFLAGS)

 # And the libraries to include
-_PythonMagick_la_LIBADD = pythonmagick_src/libpymagick.la helpers_src/libhelper.la $(BOOST_LDFLAGS) -lboost_python $(MAGICKPP_LIBS) $(MAGICK_LIBS)
+_PythonMagick_la_LIBADD = pythonmagick_src/libpymagick.la helpers_src/libhelper.la $(BOOST_LDFLAGS) -l$(BOOST_PYTHON_LIB) $(MAGICKPP_LIBS) $(MAGICK_LIBS)

 EXTRA_DIST = autogen.pl SConstruct pyste_src LICENSE

**Comment by mikayla-grace** [comment]
We applied the patch you submitted.  Thanks.
